# Generated by Django 5.2.6 on 2025-09-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('baju', 'Baju'), ('update', 'Update'), ('exclusive', 'Exclusive'), ('laptop', 'Laptop'), ('domain', 'Domain'), ('trend', 'Trend')], default='update', max_length=20),
        ),
    ]
