# Generated by Django 5.2.6 on 2025-09-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('pakaian', 'Pakaian'), ('exclusive', 'Exclusive'), ('elektronik', 'Elektronik'), ('makanan', 'Makanan'), ('minuman', 'Minuman'), ('aksesoris', 'Aksesoris'), ('trend', 'Trend')], default='update', max_length=20),
        ),
    ]
